[build]
  base = "front/"
  publish = "dist/"
[build.environment]
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "14.17.3"
  API_URL = "https://supplebox.herokuapp.com"
  GOOGLE_ANALYTICS_ID = "UA-118701335-5"
  